-- MySQL Script generated by MySQL Workbench
-- 01/29/16 14:41:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tradunio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tradunio` ;

-- -----------------------------------------------------
-- Schema tradunio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tradunio` DEFAULT CHARACTER SET utf8 ;
USE `tradunio` ;

-- -----------------------------------------------------
-- Table `tradunio`.`clubs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`clubs` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`clubs` (
  `idcl` INT(10) NOT NULL COMMENT 'Club id',
  `name` VARCHAR(25) NOT NULL COMMENT 'Club name',
  PRIMARY KEY (`idcl`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`players` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`players` (
  `idp` INT(10) NOT NULL COMMENT 'ID del jugador',
  `name` VARCHAR(25) NOT NULL COMMENT 'Nombre',
  `position` VARCHAR(25) NOT NULL COMMENT 'Demarcación del jugador',
  `idcl` INT(10) NULL COMMENT 'ID del club',
  PRIMARY KEY (`idp`),
  INDEX `idcl` (`idcl` ASC),
  CONSTRAINT `players_fk_idcl`
    FOREIGN KEY (`idcl`)
    REFERENCES `tradunio`.`clubs` (`idcl`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`users` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`users` (
  `idu` INT(10) NOT NULL,
  `name` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idu`, `name`),
  UNIQUE INDEX `idu` (`idu` ASC),
  INDEX `idu_2` (`idu` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`owners` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`owners` (
  `idp` INT(10) NOT NULL,
  `idu` INT(10) NOT NULL,
  PRIMARY KEY (`idp`, `idu`),
  INDEX `owners_fk_idu` (`idu` ASC),
  CONSTRAINT `owners_fk_idp`
    FOREIGN KEY (`idp`)
    REFERENCES `tradunio`.`players` (`idp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `owners_fk_idu`
    FOREIGN KEY (`idu`)
    REFERENCES `tradunio`.`users` (`idu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`points` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`points` (
  `idp` INT(10) NOT NULL,
  `gameday` INT(10) NOT NULL COMMENT 'ID jornada',
  `points` INT(10) NOT NULL,
  PRIMARY KEY (`idp`, `gameday`),
  CONSTRAINT `points_fk_idp`
    FOREIGN KEY (`idp`)
    REFERENCES `tradunio`.`players` (`idp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`prices` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`prices` (
  `idp` INT(10) NOT NULL,
  `date` DATE NOT NULL,
  `price` INT(10) NOT NULL,
  PRIMARY KEY (`idp`, `date`),
  CONSTRAINT `prices_idp_fk`
    FOREIGN KEY (`idp`)
    REFERENCES `tradunio`.`players` (`idp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`transactions` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`transactions` (
  `idp` INT(10) NOT NULL,
  `idu` INT(10) NOT NULL,
  `type` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL COMMENT 'Buy/Sell',
  `price` INT(10) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idp`, `idu`, `date`),
  UNIQUE INDEX `idp` (`idp` ASC, `date` ASC),
  INDEX `idp_2` (`idp` ASC),
  INDEX `transactions_idu_fk` (`idu` ASC),
  CONSTRAINT `transactions_idp_fk`
    FOREIGN KEY (`idp`)
    REFERENCES `tradunio`.`players` (`idp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transactions_idu_fk`
    FOREIGN KEY (`idu`)
    REFERENCES `tradunio`.`users` (`idu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tradunio`.`user_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tradunio`.`user_data` ;

CREATE TABLE IF NOT EXISTS `tradunio`.`user_data` (
  `idu` INT NOT NULL,
  `date` DATE NOT NULL,
  `points` INT NOT NULL,
  `money` INT NOT NULL,
  `teamvalue` INT NOT NULL,
  PRIMARY KEY (`idu`, `date`),
  CONSTRAINT `idu_users`
    FOREIGN KEY (`idu`)
    REFERENCES `tradunio`.`users` (`idu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
